stages:
  - build
  - deploy

docker build_devel:
  stage: build
  except:
  - schedules
  only:
  - xacc-devel
  script:
  - cd docker/ci/ubuntu1804/devel && docker build -t xacc/devel-ci . --no-cache

docker build_master:
  stage: build
  except:
  - schedules
  only:
  - master
  script:
  - cd docker/ci/ubuntu1804/master && docker build -t xacc/master-ci . --no-cache
  - git config remote.aideqc.url >&- || git remote add -t master aideqc https://amccaskey:$AIDEQC_ACCESS_TOKEN@github.com/aide-qc/xacc
  - git push -f aideqc HEAD:master
  - git remote remove aideqc
  # - git clone https://github.com/aide-qc/homebrew-deploy && cd homebrew-deploy 
  # - git clone --depth=1 --recursive https://github.com/eclipse/xacc
  # - tar -czvf xacc-1.0.0.tar.gz xacc
  # - jfrog bt u --override --publish xacc-1.0.0.tar.gz amccaskey/qci-homebrew-bintray/xacc-source/xacc-1.0.0
  # - export src_sha=$(sha256sum xacc-1.0.0.tar.gz | cut -d " " -f 1)
  # - sed -i "0,/sha256 \".*\"/s//sha256 \"$src_sha\" /" Formula/xacc.rb
  # - git add Formula/xacc.rb
  # - git commit -m "updating sha256 for xacc homebrew formula"
  # - git config remote.aideqchbdeploy.url >&- || git remote add -t master aideqchbdeploy https://amccaskey:$AIDEQC_ACCESS_TOKEN@github.com/aide-qc/homebrew-deploy
  # - git push -f aideqchbdeploy HEAD:master
  # - git remote remove aideqchbdeploy

docker run_docker_deploy:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/deploy/dev && docker build -t xacc/xacc . --no-cache
  - echo "$REGISTRY_PASSWORD" | docker login -u xacc --password-stdin
  - docker push xacc/xacc
